# WARNING:
#
# Do not change this file directly.  Make all project-level customizations in
# the base .rubocop.yml file

require:
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

RSpec:
  Include:
    - _spec.rb
    - "(?:^|/)spec/"

RSpec/BeEq: # new in 2.9.0
  Enabled: true

RSpec/BeNil: # new in 2.9.0
  Enabled: true

RSpec/ChangeByZero: # new in 2.11.0
  Enabled: true

RSpec/ClassCheck: # new in 2.13
  Enabled: true

RSpec/DuplicatedMetadata: # new in 2.16
  Enabled: true

RSpec/FactoryBot:
  Include:
    - spec/factories.rb
    - spec/factories/**/*.rb
    - features/support/factories/**/*.rb

RSpec/ExcessiveDocstringSpacing: # new in 2.5
  Enabled: true

RSpec/IdenticalEqualityAssertion: # new in 2.4
  Enabled: true

RSpec/NoExpectationExample: # new in 2.13
  Enabled: true

RSpec/PendingWithoutReason: # new in 2.16
  Enabled: true

RSpec/SortMetadata: # new in 2.14
  Enabled: true

RSpec/SubjectDeclaration: # new in 2.5
  Enabled: true

RSpec/VerifiedDoubleReference: # new in 2.10.0
  Enabled: true

########## RSpec/Capybara/*

RSpec/Capybara/NegationMatcher: # new in 2.14
  Enabled: true

RSpec/Capybara/SpecificActions: # new in 2.14
  Enabled: true

RSpec/Capybara/SpecificFinders: # new in 2.13
  Enabled: true

RSpec/Capybara/SpecificMatcher: # new in 2.12
  Enabled: true

######### RSpec/Rails/*

RSpec/Rails/AvoidSetupHook: # new in 2.4
  Enabled: true

RSpec/Rails/HaveHttpStatus: # new in 2.12
  Enabled: true

RSpec/Rails/InferredSpecType: # new in 2.14
  Enabled: false

######### RSpec/FactoryBot/*

RSpec/FactoryBot/ConsistentParenthesesStyle: # new in 2.14
  Enabled: true

RSpec/FactoryBot/FactoryNameStyle: # new in 2.16
  Enabled: true

RSpec/FactoryBot/SyntaxMethods: # new in 2.7
  Enabled: true
